#!/usr/bin/env python3
"""
🔱 Veil Sentinel Auto‑Hardener

Single‑file hardener that enforces a canonical FastAPI `app/main.py`
inside a target project directory.

- Embedded template for app/main.py
- Unified diff output
- Dry‑run vs write mode
- Linux‑native paths only
"""

import argparse
import datetime
import difflib
from pathlib import Path
from typing import Tuple


# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def log(msg: str) -> None:
    print(f"[{_now_iso()}] {msg}")


# ---------------------------------------------------------------------------
# Canonical template for app/main.py
# ---------------------------------------------------------------------------

MAIN_REL_PATH = Path("app/main.py")

MAIN_TEMPLATE = """# 🔱 Auto‑generated by Veil Sentinel Hardener
# Do not edit manually — changes will be overwritten.

from fastapi import FastAPI, APIRouter
import logging
from contextlib import asynccontextmanager

logger = logging.getLogger("veil.app")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

router = APIRouter()


@router.get("/health", tags=["health"])
async def health_check():
    return {"status": "ok"}


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("🔱 Veil app starting up")
    try:
        yield
    finally:
        logger.info("🔱 Veil app shutting down")


app = FastAPI(
    title="Veil Service",
    version="1.0.0",
    lifespan=lifespan,
)

app.include_router(router)
"""


# ---------------------------------------------------------------------------
# Core hardener logic
# ---------------------------------------------------------------------------

def compute_diff(current: str, desired: str, rel_path: Path) -> str:
    current_lines = current.splitlines(keepends=True)
    desired_lines = desired.splitlines(keepends=True)
    diff = difflib.unified_diff(
        current_lines,
        desired_lines,
        fromfile=f"{rel_path}",
        tofile=f"{rel_path}",
    )
    return "".join(diff)


def ensure_main(target_root: Path, dry_run: bool) -> Tuple[bool, bool]:
    """
    Ensure app/main.py matches MAIN_TEMPLATE.

    Returns:
        (changed, created)
    """
    target_path = target_root / MAIN_REL_PATH
    rel_display = MAIN_REL_PATH

    # Ensure parent directory exists
    target_path.parent.mkdir(parents=True, exist_ok=True)

    if target_path.exists():
        current = target_path.read_text(encoding="utf-8")
        if current == MAIN_TEMPLATE:
            return False, False

        log(f"[DIFF] {rel_display}")
        diff = compute_diff(current, MAIN_TEMPLATE, rel_display)
        print(diff, end="")

        if dry_run:
            log(f"[DRY‑RUN] Would write {target_path}")
        else:
            target_path.write_text(MAIN_TEMPLATE, encoding="utf-8")
            log(f"[WRITE] Wrote {target_path}")
        return True, False

    # File does not exist — create it
    log(f"[DIFF] {rel_display}")
    diff = compute_diff("", MAIN_TEMPLATE, rel_display)
    print(diff, end="")

    if dry_run:
        log(f"[DRY‑RUN] Would write {target_path}")
    else:
        target_path.write_text(MAIN_TEMPLATE, encoding="utf-8")
        log(f"[WRITE] Wrote {target_path}")
    return True, True


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Veil Sentinel Auto‑Hardener (FastAPI main.py generator)"
    )
    parser.add_argument(
        "--target",
        required=True,
        help="Linux-native target project root directory (e.g. /home/user/veil_os/projects/my_service)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show diffs but do not write any files",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    target_root = Path(args.target).resolve()

    log("🔱 Starting Veil Sentinel Hardening Pass")

    if not target_root.exists():
        log(f"Target directory does not exist. Creating: {target_root}")
        target_root.mkdir(parents=True, exist_ok=True)

    if not target_root.is_dir():
        raise SystemExit(f"Target path is not a directory: {target_root}")

    changed, created = ensure_main(target_root, dry_run=args.dry_run)

    if not changed:
        log("No changes required for app/main.py")

    log("🔱 Hardening complete")


if __name__ == "__main__":
    main()
