#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
ORGANS_DIR = ROOT / "organs"
README = ROOT / "README.md"

# Treat these as non-organs (repo glue / assets / files)
EXCLUDE_NAMES = {
    "__pycache__",
}
EXCLUDE_SUFFIXES = ("_assets",)
EXCLUDE_FILES = (".py",)  # orchestrator.py etc

def list_organs() -> list[str]:
    if not ORGANS_DIR.exists():
        print("ERROR: organs/ directory not found", file=sys.stderr)
        sys.exit(1)

    names = []
    for p in ORGANS_DIR.iterdir():
        n = p.name
        if n in EXCLUDE_NAMES:
            continue
        if any(n.endswith(suf) for suf in EXCLUDE_SUFFIXES):
            continue
        if p.is_file() and any(n.endswith(ext) for ext in EXCLUDE_FILES):
            continue
        # count only directories as "organs"
        if p.is_dir():
            names.append(n)

    return sorted(names)

def tier_guess(name: str) -> str:
    # Lightweight heuristic just to bucket for README.
    # You can refine later by using a registry/spec file.
    p0 = {"guardian","sentinel","cortex","audit","firewall","admission","rbac","mfa","vault","watchdog","zero_trust","quarantine","backup","insider_threat"}
    p1 = {"epic","imprivata","hl7","fhir","dicom","dlp","gateway","forensic","telemetry","analytics","hospital","fabric","monitor","security"}
    n = name.lower()
    if n in p0:
        return "P0"
    if n in p1:
        return "P1"
    return "P2"

def replace_badge(md: str, count: int) -> str:
    # update shield "Organs-XX Active"
    md = re.sub(r'(https://img\.shields\.io/badge/Organs-)\d+%20Active',
                rf'\g<1>{count}%20Active', md)
    # update textual "82 specialized security organs", etc.
    md = re.sub(r'\b\d+\s+specialized security organs\b', f'{count} specialized security organs', md)
    md = re.sub(r'\bThe\s+\d+\s+Organs\b', f'The {count} Organs', md)
    return md

def fix_html_hr(md: str) -> str:
    # GitHub render breaker: </p> immediately followed by ---
    return re.sub(r'</p>\n---', '</p>\n\n---', md)

def inject_autolist(md: str, organs: list[str]) -> str:
    """
    Replace the section between markers with an auto-generated list.
    Add these markers once in README:

    <!-- ORGANS:BEGIN -->
    ...
    <!-- ORGANS:END -->
    """
    begin = "<!-- ORGANS:BEGIN -->"
    end = "<!-- ORGANS:END -->"
    if begin not in md or end not in md:
        # If markers don't exist, append a section at the end of "The XX Organs"
        # but we won't guess where; just add markers after first occurrence.
        pat = r'(##\s+The\s+\d+\s+Organs[^\n]*\n)'
        m = re.search(pat, md)
        if not m:
            print("ERROR: Could not find '## The <N> Organs' header, add markers manually.", file=sys.stderr)
            sys.exit(2)
        insert_at = m.end()
        md = md[:insert_at] + f"\n{begin}\n{end}\n" + md[insert_at:]

    # Build markdown tables by tier (names only; you can add functions later)
    p0 = [o for o in organs if tier_guess(o) == "P0"]
    p1 = [o for o in organs if tier_guess(o) == "P1"]
    p2 = [o for o in organs if tier_guess(o) == "P2"]

    def table(title: str, items: list[str]) -> str:
        rows = "\n".join([f"| `{x}` |" for x in items]) if items else "| _(none)_ |"
        return (
            f"### {title}\n\n"
            "| Organ |\n"
            "|---|\n"
            f"{rows}\n"
        )

    body = (
        "<!-- This block is auto-generated by scripts/sync_readme_organs.py -->\n\n"
        f"**Total organs (from `organs/`): {len(organs)}**\n\n"
        + table("P0 — Critical", p0)
        + "\n"
        + table("P1 — Important", p1)
        + "\n"
        + "<details>\n<summary>View all P2 organs</summary>\n\n"
        + table("P2 — Standard", p2)
        + "\n</details>\n"
    )

    md = re.sub(re.escape(begin) + r".*?" + re.escape(end),
                begin + "\n\n" + body + "\n" + end,
                md, flags=re.S)
    return md

def main() -> int:
    organs = list_organs()
    md = README.read_text(encoding="utf-8")

    md = fix_html_hr(md)
    md = replace_badge(md, len(organs))
    md = inject_autolist(md, organs)

    README.write_text(md, encoding="utf-8")
    print(f"OK: synced README to {len(organs)} organs from {ORGANS_DIR}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
